"""Markdown output — assembles the final report from pipeline stages."""

from __future__ import annotations

from pathlib import Path


def assemble_report(
    thesis: str,
    executive_summary: str,
    timeline: str,
    claim_analyses: list[dict],
    synthesis: str,
    recommendations: str,
) -> str:
    """Assemble a complete markdown report from pipeline outputs."""
    sections = []

    sections.append(f"# Thesis Validation: {thesis}")
    sections.append(f"*Generated by Gildea Intelligence*\n")

    # Executive Summary (answer first — pyramid principle)
    sections.append("## Executive Summary")
    sections.append(executive_summary)

    # Event Timeline
    sections.append("## Event Timeline")
    sections.append(timeline)

    # Claim-by-Claim Analysis
    sections.append("## Claim-by-Claim Analysis")
    for i, ca in enumerate(claim_analyses, 1):
        badge = _assessment_badge(ca.get("assessment", "INSUFFICIENT"))
        sections.append(f"### Claim {i}: {ca['claim']}")
        sections.append(
            f"**Assessment:** {badge} "
            f"({ca.get('support_count', 0)} sources support, "
            f"{ca.get('contradict_count', 0)} contradict)"
        )

        # Supporting evidence
        supporting = ca.get("supporting_evidence", [])
        if supporting:
            sections.append("\n**Supporting evidence:**")
            for ev in supporting:
                sections.append(
                    f"- *{ev.get('signal_title', '')}* ({ev.get('source', '')}): "
                    f'"{ev.get("text", "")}"'
                )

        # Contradicting evidence
        contradicting = ca.get("contradicting_evidence", [])
        if contradicting:
            sections.append("\n**Contradicting evidence:**")
            for ev in contradicting:
                sections.append(
                    f"- *{ev.get('signal_title', '')}* ({ev.get('source', '')}): "
                    f'"{ev.get("text", "")}"'
                )

        # Narrative
        narrative = ca.get("narrative", "")
        if narrative:
            sections.append(f"\n{narrative}")

    # Synthesis
    sections.append("## Synthesis")
    sections.append(synthesis)

    # Recommendations
    sections.append("## Recommendations")
    sections.append(recommendations)

    # Methodology
    sections.append("## Methodology")
    sections.append(
        "This report was generated using Gildea's verified AI market intelligence, "
        "which tracks 500+ expert sources with structured decomposition and independent "
        "evidence verification. Every claim cited has passed factual consistency scoring "
        "against source material. Consensus counts represent independent publications "
        "confirming the same claim through cross-source vector similarity mapping."
    )

    return "\n\n".join(sections)


def write_report(report: str, path: Path) -> None:
    """Write the report to a markdown file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(report, encoding="utf-8")


def _assessment_badge(assessment: str) -> str:
    badges = {
        "SUPPORTED": "SUPPORTED",
        "CONTESTED": "CONTESTED",
        "INSUFFICIENT": "INSUFFICIENT EVIDENCE",
        "CONTRADICTED": "CONTRADICTED",
    }
    return badges.get(assessment, assessment)
